apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  wildcardDomain: '{{ (lookup "operator.openshift.io/v1" "IngressController" "openshift-ingress-operator" "default").status.domain }}'
  resourceRequirementsEnabled: false
  tenantName: maas
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: {{ .Values.storageClassName }}
  apicast:
    stagingSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
             name: llm-metrics
    productionSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
             name: llm-metrics 