apiVersion: capabilities.3scale.net/v1beta1
kind: CustomPolicyDefinition
metadata:
  name: llm-metrics
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: LLM Metrics
  version: "1.0.0"
  schema:
    name: LLM Metrics Policy
    version: "1.0.0"
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    properties:
      llm:
        type: object
        properties:
          provider:
            type: string
          model:
            type: string
          type:
            type: string 