apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: models-as-a-service
spec:
  generators:
    - git:
        #repoURL: https://github.com/redhat-ai-services/ai-accelerator-examples.git
        #revision: maas
        repoURL: https://github.com/sukantadash/ai-accelerator-examples-maas.git
        revision: main
        directories:
          - path: examples/models-as-a-service/components/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/part-of: models-as-a-service
    spec:
      project: models-as-a-service
      source:
        #repoURL: https://github.com/redhat-ai-services/ai-accelerator-examples.git
        #revision: maas
        repoURL: https://github.com/sukantadash/ai-accelerator-examples-maas.git
        revision: main
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}-release'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename | replace "-instance" "" | replace "-operator" "" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: apps.3scale.net
        kind: APIManager
        jsonPointers:
        - /spec/wildcardDomain