apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: models-as-a-service
spec:
  description: "Applications for the Models as a Service example"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*' 